<?xml version="1.0" encoding="utf-8"?><Database Name="QLKS" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-UNGM53F\SQLEXPRESS;Initial Catalog=QLKS;Integrated Security=True" SettingsObjectName="QLKHACHSAN.Properties.Settings" SettingsPropertyName="QLKSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QUOCTICH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PASSPORT" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>